use crate::export::{self, BlockContext};
use crate::models::{Agent, SyncAction, SyncKind, SyncOp, SyncReport};
use crate::{AtlasError, Result};
use std::path::{Path, PathBuf};

/// Inputs describing one sync pass: the repo (or, for a global sync, home
/// directory) root, the agents to export, the managed-block context, and
/// which targets to write.
pub struct SyncInputs<'a> {
    pub root: &'a Path,
    pub agents: &'a [Agent],
    pub block: BlockContext,
    pub targets: &'a [SyncKind],
}

/// Computes what a sync would do, without touching the filesystem beyond
/// reading existing files to decide each op's action.
pub fn plan_sync(i: &SyncInputs) -> Result<Vec<SyncOp>> {
    let mut ops = Vec::new();
    for kind in i.targets {
        match kind {
            SyncKind::Claude => {
                for a in i.agents {
                    let path = i.root.join(".claude/agents").join(format!("{}.md", a.name));
                    ops.push(agent_op(*kind, path, export::claude_agent_md(a))?);
                }
            }
            SyncKind::Codex => {
                for a in i.agents {
                    let path = i.root.join(".codex/agents").join(format!("{}.toml", a.name));
                    ops.push(agent_op(*kind, path, export::codex_agent_toml(a))?);
                }
            }
            SyncKind::AgentsMd => ops.push(block_op(*kind, i.root.join("AGENTS.md"), &i.block)?),
            SyncKind::ClaudeMd => ops.push(block_op(*kind, i.root.join("CLAUDE.md"), &i.block)?),
        }
    }
    Ok(ops)
}

/// An exporter-owned file (`.claude/agents/*.md`, `.codex/agents/*.toml`):
/// refuses to overwrite a hand-written file that doesn't carry the generated
/// header.
fn agent_op(kind: SyncKind, path: PathBuf, content: String) -> Result<SyncOp> {
    let action = if !path.exists() {
        SyncAction::Create
    } else {
        let existing = std::fs::read_to_string(&path)?;
        if !export::is_generated(&existing) {
            SyncAction::Skip("not generated by atlas".into())
        } else if existing == content {
            SyncAction::Unchanged
        } else {
            SyncAction::Update
        }
    };
    Ok(SyncOp { kind, path, content, action })
}

/// A managed-block file (`AGENTS.md`, `CLAUDE.md`): the file itself is
/// user-owned, only the block between the markers is atlas-managed, so it is
/// never skipped.
fn block_op(kind: SyncKind, path: PathBuf, block: &BlockContext) -> Result<SyncOp> {
    let existed = path.exists();
    let existing = if existed { std::fs::read_to_string(&path)? } else { String::new() };
    // `render_block` ends with a trailing newline after `END`; `splice_block`
    // expects a bare marker-delimited block and owns newline placement
    // itself, so strip it before handing the block over.
    let rendered = export::render_block(block);
    let content = export::splice_block(&existing, rendered.trim_end());
    let action = if !existed {
        SyncAction::Create
    } else if existing == content {
        SyncAction::Unchanged
    } else {
        SyncAction::Update
    };
    Ok(SyncOp { kind, path, content, action })
}

/// Writes every `Create`/`Update` op to disk, creating parent directories as
/// needed, then returns the tally. Stops at the first write failure and
/// reports the failing path plus how many of the planned writes had already
/// completed, since a bare io error gives no way to tell which file or how
/// much progress was made.
pub fn apply(ops: &[SyncOp]) -> Result<SyncReport> {
    let total = ops.iter().filter(|o| matches!(o.action, SyncAction::Create | SyncAction::Update)).count();
    let mut done = 0usize;
    for op in ops {
        if matches!(op.action, SyncAction::Create | SyncAction::Update) {
            let write = || -> std::io::Result<()> {
                if let Some(parent) = op.path.parent() {
                    std::fs::create_dir_all(parent)?;
                }
                std::fs::write(&op.path, &op.content)
            };
            write().map_err(|e| {
                AtlasError::Other(format!("sync: failed to write {}: {e} ({done} of {total} files written)", op.path.display()))
            })?;
            done += 1;
        }
    }
    Ok(summarize(ops))
}

/// Tallies a set of ops into a report without writing anything.
pub fn summarize(ops: &[SyncOp]) -> SyncReport {
    let mut report = SyncReport { ops: ops.to_vec(), ..Default::default() };
    for op in ops {
        match &op.action {
            SyncAction::Create => report.created += 1,
            SyncAction::Update => report.updated += 1,
            SyncAction::Unchanged => report.unchanged += 1,
            SyncAction::Skip(_) => report.skipped += 1,
        }
    }
    report
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::export::BlockContext;
    use crate::models::*;

    fn agent(name: &str) -> Agent {
        Agent {
            id: uuid::Uuid::nil(),
            name: name.into(),
            description: "d".into(),
            instructions: "i".into(),
            model_hint: None,
            tools: vec![],
            tags: vec![],
            version: 1,
            created_at: Default::default(),
            updated_at: Default::default(),
        }
    }

    #[test]
    fn plan_apply_and_replan_is_unchanged() {
        let d = tempfile::tempdir().unwrap();
        std::fs::write(d.path().join("AGENTS.md"), "# Repo rules\n\nkeep\n").unwrap();
        std::fs::create_dir_all(d.path().join(".claude/agents")).unwrap();
        std::fs::write(d.path().join(".claude/agents/handwritten.md"), "---\nname: handwritten\n---\nmine\n").unwrap();
        let agents = vec![agent("reviewer"), agent("handwritten")];
        let inputs = SyncInputs {
            root: d.path(),
            agents: &agents,
            block: BlockContext { mcp_command: "atlas mcp".into(), agents: agents.clone(), practices: vec![], project_name: Some("p".into()) },
            targets: &[SyncKind::Claude, SyncKind::Codex, SyncKind::AgentsMd, SyncKind::ClaudeMd],
        };
        let ops = plan_sync(&inputs).unwrap();
        assert!(ops.iter().any(|o| o.kind == SyncKind::Claude && o.path.ends_with("reviewer.md") && o.action == SyncAction::Create));
        assert!(ops.iter().any(|o| o.path.ends_with("handwritten.md") && matches!(o.action, SyncAction::Skip(_))), "refuses to overwrite non-generated file");
        assert!(ops.iter().any(|o| o.kind == SyncKind::AgentsMd && o.action == SyncAction::Update));
        assert!(ops.iter().any(|o| o.kind == SyncKind::ClaudeMd && o.action == SyncAction::Create));
        let rep = apply(&ops).unwrap();
        assert_eq!(rep.skipped, 1);
        let agents_md = std::fs::read_to_string(d.path().join("AGENTS.md")).unwrap();
        assert!(agents_md.starts_with("# Repo rules\n\nkeep\n") && agents_md.contains("<!-- atlas:start -->"));
        assert_eq!(std::fs::read_to_string(d.path().join(".claude/agents/handwritten.md")).unwrap(), "---\nname: handwritten\n---\nmine\n");
        let again = plan_sync(&inputs).unwrap();
        assert!(again.iter().filter(|o| !matches!(o.action, SyncAction::Skip(_))).all(|o| o.action == SyncAction::Unchanged));
    }

    #[test]
    fn apply_wraps_write_error_with_path_and_progress() {
        let d = tempfile::tempdir().unwrap();
        let good1 = d.path().join(".claude/agents/first.md");
        let bad = d.path().join(".claude/agents/reviewer.md");
        let good2 = d.path().join(".claude/agents/third.md");
        // Make the second target unwritable: a directory sits where the file should go.
        std::fs::create_dir_all(&bad).unwrap();
        let ops = vec![
            SyncOp { kind: SyncKind::Claude, path: good1.clone(), content: "one".into(), action: SyncAction::Create },
            SyncOp { kind: SyncKind::Claude, path: bad.clone(), content: "two".into(), action: SyncAction::Create },
            SyncOp { kind: SyncKind::Claude, path: good2.clone(), content: "three".into(), action: SyncAction::Create },
        ];
        let err = apply(&ops).unwrap_err();
        let msg = err.to_string();
        assert!(msg.contains(&bad.display().to_string()), "message should name the failing path: {msg}");
        assert!(msg.contains("1 of 3 files written"), "message should report progress: {msg}");
        assert_eq!(std::fs::read_to_string(&good1).unwrap(), "one", "earlier op should still have been written");
        assert!(!good2.exists(), "later op should not have been attempted after the failure");
    }
}
