pub mod claude;
pub mod managed_block;
pub mod persona;

pub use managed_block::{render_block, render_block_with, splice_block, BlockContext, END, START};
pub use persona::{agents_md_sections, claude_md_personas, claude_subagent, is_agent_export};

pub const GENERATED_HEADER: &str = "generated by atlas; edit in Atlas, not here";

/// True when the first few lines carry [`GENERATED_HEADER`], meaning the file
/// was produced by an exporter and is safe for `sync` to overwrite.
pub fn is_generated(content: &str) -> bool {
    content.lines().take(3).any(|l| l.contains(GENERATED_HEADER))
}
