pub mod claude;
pub mod codex;
pub mod managed_block;

pub use claude::claude_agent_md;
pub use codex::codex_agent_toml;
pub use managed_block::{render_block, splice_block, BlockContext, END, START};

pub const GENERATED_HEADER: &str = "generated by atlas; edit in Atlas, not here";

/// True when the first few lines carry [`GENERATED_HEADER`], meaning the file
/// was produced by an exporter and is safe for `sync` to overwrite.
pub fn is_generated(content: &str) -> bool {
    content.lines().take(3).any(|l| l.contains(GENERATED_HEADER))
}
