#!/usr/bin/env node
// Extracts the per-component CSS out of the DBMan design system React bundle.
//
// The bundle stores every component as `// components/<dir>/<Name>.jsx` followed by an
// IIFE whose first statement is `const CSS = ` + a template literal. That literal is the
// only place the component CSS lives, so we slice it out here and write one stylesheet
// the Svelte port can import. Re-runnable: it always rewrites the whole output file.
//
// Usage: node scripts/extract-ds-css.mjs [path/to/_ds_bundle.js] [path/to/output.css]

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const repo = resolve(here, '..');

const DEFAULT_BUNDLE = resolve(
	repo,
	'references/Atlas Desktop UI Design File/_ds',
	'dbman-design-system-c4e4e5f5-d936-46db-9e21-75bddd719275/_ds_bundle.js'
);

const DEFAULT_OUTPUT = resolve(repo, 'src/lib/ds/dbman.css');

// Order matters: it is the cascade order of the generated file.
const COMPONENTS = [
	'components/core/Button.jsx',
	'components/core/IconButton.jsx',
	'components/core/Input.jsx',
	'components/core/Select.jsx',
	'components/core/Checkbox.jsx',
	'components/core/Badge.jsx',
	'components/core/KeyHint.jsx',
	'components/core/Skeleton.jsx',
	'components/navigation/TitleBar.jsx',
	'components/navigation/ActivityRail.jsx',
	'components/overlay/Tooltip.jsx',
	'components/overlay/Menu.jsx',
	'components/overlay/Modal.jsx'
];

/**
 * Returns the CSS template literal that follows the given component marker, or null when
 * that component ships none. The search is bounded by the next component marker, so a
 * component without a CSS literal can never pick up the following component's.
 */
function sliceCss(bundle, marker) {
	const at = bundle.indexOf(`// ${marker}`);
	if (at === -1) throw new Error(`marker not found in bundle: ${marker}`);

	const nextMarker = bundle.indexOf('\n// components/', at + 1);
	const limit = nextMarker === -1 ? bundle.length : nextMarker;

	const open = bundle.indexOf('const CSS = `', at);
	if (open === -1 || open > limit) return null;

	const start = open + 'const CSS = `'.length;
	const end = bundle.indexOf('`;', start);
	if (end === -1 || end > limit) throw new Error(`unterminated CSS literal for: ${marker}`);

	// The bundle escapes nothing but backticks inside these literals.
	return bundle.slice(start, end).replace(/\\`/g, '`').trim();
}

const bundlePath = process.argv[2] ? resolve(process.argv[2]) : DEFAULT_BUNDLE;
const outputPath = process.argv[3] ? resolve(process.argv[3]) : DEFAULT_OUTPUT;
const bundle = readFileSync(bundlePath, 'utf8');

const sourceLabel = bundlePath.startsWith(repo) ? bundlePath.slice(repo.length + 1) : bundlePath;

const written = [];
const sections = [];

for (const marker of COMPONENTS) {
	const css = sliceCss(bundle, marker);
	if (css === null) {
		process.stderr.write(`skipped ${marker}: no CSS literal in the bundle\n`);
		continue;
	}
	written.push(marker);
	sections.push(`/* ${marker} */`, css, '');
}

const parts = [
	'/* Generated by scripts/extract-ds-css.mjs. Do not edit by hand.',
	' *',
	` * Source: ${sourceLabel}`,
	' * Components, in cascade order:',
	...written.map((c) => ` *   ${c}`),
	' */',
	'',
	...sections
];

mkdirSync(dirname(outputPath), { recursive: true });
writeFileSync(outputPath, parts.join('\n'), 'utf8');

const rel = outputPath.startsWith(repo) ? outputPath.slice(repo.length + 1) : outputPath;
process.stdout.write(`wrote ${rel} (${written.length} components)\n`);
