#!/usr/bin/env node
// Extracts the per-component CSS out of the DBMan design system React bundle.
//
// The bundle stores every component as `// components/<dir>/<Name>.jsx` followed by an
// IIFE whose first statement is `const CSS = ` + a template literal. That literal is the
// only place the component CSS lives, so we slice it out here and write one stylesheet
// the Svelte port can import. Re-runnable: it always rewrites the whole output file.
//
// Usage: node scripts/extract-ds-css.mjs [path/to/_ds_bundle.js]

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const repo = resolve(here, '..');

const DEFAULT_BUNDLE = resolve(
	repo,
	'references/Atlas Desktop UI Design File/_ds',
	'dbman-design-system-c4e4e5f5-d936-46db-9e21-75bddd719275/_ds_bundle.js'
);

const OUTPUT = resolve(repo, 'src/lib/ds/dbman.css');

// Order matters: it is the cascade order of the generated file.
const COMPONENTS = [
	'components/core/Button.jsx',
	'components/core/IconButton.jsx',
	'components/core/Input.jsx',
	'components/core/Select.jsx',
	'components/core/Checkbox.jsx',
	'components/core/Badge.jsx',
	'components/core/KeyHint.jsx',
	'components/core/Skeleton.jsx',
	'components/navigation/TitleBar.jsx',
	'components/navigation/ActivityRail.jsx',
	'components/overlay/Tooltip.jsx',
	'components/overlay/Menu.jsx',
	'components/overlay/Modal.jsx'
];

/** Returns the CSS template literal that follows the given component marker. */
function sliceCss(bundle, marker) {
	const at = bundle.indexOf(`// ${marker}`);
	if (at === -1) throw new Error(`marker not found in bundle: ${marker}`);

	const open = bundle.indexOf('const CSS = `', at);
	if (open === -1) throw new Error(`no CSS literal after marker: ${marker}`);

	const start = open + 'const CSS = `'.length;
	const end = bundle.indexOf('`;', start);
	if (end === -1) throw new Error(`unterminated CSS literal for: ${marker}`);

	// The bundle escapes nothing but backticks inside these literals.
	return bundle.slice(start, end).replace(/\\`/g, '`').trim();
}

const bundlePath = process.argv[2] ? resolve(process.argv[2]) : DEFAULT_BUNDLE;
const bundle = readFileSync(bundlePath, 'utf8');

const sourceLabel = bundlePath.startsWith(repo) ? bundlePath.slice(repo.length + 1) : bundlePath;

const parts = [
	'/* Generated by scripts/extract-ds-css.mjs. Do not edit by hand.',
	' *',
	` * Source: ${sourceLabel}`,
	' * Components, in cascade order:',
	...COMPONENTS.map((c) => ` *   ${c}`),
	' */',
	''
];

for (const marker of COMPONENTS) {
	parts.push(`/* ${marker} */`, sliceCss(bundle, marker), '');
}

mkdirSync(dirname(OUTPUT), { recursive: true });
writeFileSync(OUTPUT, parts.join('\n'), 'utf8');

const rel = OUTPUT.slice(repo.length + 1);
process.stdout.write(`wrote ${rel} (${COMPONENTS.length} components)\n`);
