<script lang="ts">
	// Exports agents into the files coding agents read. A global sync writes into
	// the home directory and the daemon drops the managed-block targets there, so
	// this panel only offers the two agent exporters in global mode.

	import { onMount } from 'svelte';
	import { api } from '$lib/daemon.svelte';
	import { errorMessage } from '$lib/errors';
	import type { Project, SyncKind, SyncOp, SyncReport } from '$lib/types';
	import { skipReason } from '$lib/types';
	import Button from '$lib/ui/Button.svelte';
	import Card from '$lib/ui/Card.svelte';
	import EmptyState from '$lib/ui/EmptyState.svelte';
	import ErrorState from '$lib/ui/ErrorState.svelte';
	import Select from '$lib/ui/Select.svelte';
	import Table, { type TableColumn } from '$lib/ui/Table.svelte';
	import { push } from '$lib/ui/toasts.svelte';

	const GLOBAL = 'global';

	const TARGETS: { kind: SyncKind; label: string; projectOnly: boolean }[] = [
		{ kind: 'claude', label: 'Claude agents', projectOnly: false },
		{ kind: 'codex', label: 'Codex agents', projectOnly: false },
		{ kind: 'agents_md', label: 'AGENTS.md block', projectOnly: true },
		{ kind: 'claude_md', label: 'CLAUDE.md block', projectOnly: true }
	];

	const COLUMNS: TableColumn[] = [
		{ key: 'path', label: 'Path' },
		{ key: 'action', label: 'Action', width: '30%' }
	];

	let projects = $state<Project[]>([]);
	let scope = $state(GLOBAL);
	let chosen = $state<SyncKind[]>(TARGETS.map((t) => t.kind));
	let running = $state(false);
	let report = $state<SyncReport | null>(null);
	let wasDryRun = $state(true);
	/** A failed sync. Kept apart from `listError` so the results only ever show sync outcomes. */
	let error = $state<string | null>(null);
	/** A failed project list, which leaves a global sync perfectly usable. */
	let listError = $state<string | null>(null);

	const isGlobal = $derived(scope === GLOBAL);
	const project = $derived(projects.find((p) => p.id === scope) ?? null);

	// Global mode has no repository to splice a managed block into.
	const enabled = $derived(
		TARGETS.filter((t) => !(isGlobal && t.projectOnly)).map((t) => t.kind)
	);
	const targets = $derived(chosen.filter((k) => enabled.includes(k)));

	const options = $derived([
		{ value: GLOBAL, label: 'Global (home directory)' },
		...projects.map((p) => ({ value: p.id, label: `${p.name} · ${p.root_path}` }))
	]);

	onMount(async () => {
		try {
			projects = await api().listProjects();
		} catch (e) {
			listError = errorMessage(e);
		}
	});

	function toggle(kind: SyncKind): void {
		const i = chosen.indexOf(kind);
		if (i >= 0) chosen.splice(i, 1);
		else chosen.push(kind);
	}

	async function run(checkOnly: boolean): Promise<void> {
		running = true;
		error = null;
		try {
			report = await api().sync({
				root: isGlobal ? null : (project?.root_path ?? null),
				global: isGlobal,
				targets,
				check_only: checkOnly
			});
			wasDryRun = checkOnly;
			if (!checkOnly) {
				const r = report;
				push('success', `Synced: ${r.created} created, ${r.updated} updated, ${r.skipped} skipped`);
			}
		} catch (e) {
			report = null;
			error = errorMessage(e);
			if (!checkOnly) push('error', error);
		} finally {
			running = false;
		}
	}

	/** "Skip: not generated by atlas" for a skip, otherwise the plain action. */
	function actionLabel(op: SyncOp): string {
		const reason = skipReason(op.action);
		return reason === null ? (op.action as string) : `Skip: ${reason}`;
	}
</script>

<Card title="Sync">
	<div class="controls">
		<label class="field">
			<span>Scope</span>
			<Select bind:value={scope} {options} data-testid="sync-scope" />
		</label>

		<fieldset class="targets">
			<legend>Targets</legend>
			{#each TARGETS as target (target.kind)}
				{@const off = isGlobal && target.projectOnly}
				<label class="check" class:off>
					<input
						type="checkbox"
						checked={chosen.includes(target.kind)}
						disabled={off}
						onchange={() => toggle(target.kind)}
					/>
					{target.label}
				</label>
			{/each}
		</fieldset>

		<div class="buttons">
			<Button
				data-testid="sync-check"
				disabled={running || targets.length === 0}
				onclick={() => run(true)}
			>
				Check
			</Button>
			<Button
				variant="primary"
				data-testid="sync-run"
				disabled={running || targets.length === 0}
				onclick={() => run(false)}
			>
				Sync
			</Button>
		</div>
	</div>

	{#if listError}
		<p class="hint bad" role="alert" data-testid="sync-list-error">
			Projects could not be listed ({listError}); only a global sync is available.
		</p>
	{/if}

	{#if isGlobal}
		<p class="hint">A global sync writes agent files into your home directory.</p>
	{:else if project}
		<p class="hint">Writes into <code>{project.root_path}</code>.</p>
	{/if}

	<div class="results" data-testid="sync-results">
		{#if error}
			<ErrorState message={error} />
		{:else if report}
			<p class="summary" data-testid="sync-summary">
				{wasDryRun ? 'Planned' : 'Done'}: {report.created} created, {report.updated} updated,
				{report.unchanged} unchanged, {report.skipped} skipped
			</p>
			<Table columns={COLUMNS} rows={report.ops} rowKey={(op) => op.path}>
				{#snippet cell(op: SyncOp, key: string)}
					{#if key === 'path'}
						<code class="path">{op.path}</code>
					{:else}
						{actionLabel(op)}
					{/if}
				{/snippet}
				{#snippet empty()}
					<EmptyState title="Nothing to write" hint="No target produced a file for this scope." />
				{/snippet}
			</Table>
		{:else}
			<EmptyState
				title="No sync run yet"
				hint="Check shows what would be written without touching any file."
			/>
		{/if}
	</div>
</Card>

<style>
	.controls {
		display: flex;
		flex-wrap: wrap;
		align-items: flex-end;
		gap: var(--space-4);
	}

	.field {
		display: flex;
		flex-direction: column;
		gap: var(--space-1);
		min-width: 280px;
		flex: 1 1 280px;
	}

	.field > span {
		font-size: 13px;
		color: var(--muted);
	}

	.targets {
		display: flex;
		flex-wrap: wrap;
		gap: var(--space-3);
		margin: 0;
		padding: 0;
		border: 0;
	}

	legend {
		padding: 0;
		font-size: 13px;
		color: var(--muted);
	}

	.check {
		display: inline-flex;
		align-items: center;
		gap: var(--space-1);
		white-space: nowrap;
	}

	.check.off {
		opacity: 0.5;
	}

	.buttons {
		display: flex;
		gap: var(--space-2);
	}

	.hint {
		margin: var(--space-3) 0 0;
		color: var(--muted);
		font-size: 13px;
	}

	.hint.bad {
		color: var(--danger);
	}

	.results {
		margin-top: var(--space-4);
	}

	.summary {
		margin: 0 0 var(--space-2);
		color: var(--muted);
		font-size: 13px;
	}

	.path {
		font-family: var(--font-mono);
		font-size: 12px;
		overflow-wrap: anywhere;
	}
</style>
